[package]
name = "rustrt"
version = "0.1.0"
authors = ["David Liljefors <david@ortolan.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stb = "0.3.2"
rand = "0.8.4"
